# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb8643d3d35756ead0ef0d1109fc51e167148afe3ec653ac9baa86cee772d755e562dc27e50c6b944e7120a313a26088ce6cc6390cf2fe4c850acb3657b32517

test:
  secret_key_base: 65d32d8e8a89d907cdf1bc3890141df43484ff349fed5d1f749b8ab86410d6e69acb774e92e47edb8d592b0cbf313ae28b12581b45db30114d29d2b69888c65f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
